### ISSUE TITLE
Sticker/Placeholder import (folder or file) buttons seem to do nothing

### ISSUE THREAD

**Issue by rsmazrab** [silveredgold/beta-protection#31]
Again v0.2 installed from unpacked directory on mac

**Comment by silveredgold** [comment]
What browser are you using?

**Comment by rsmazrab** [comment]
I'm using Brave

**Comment by silveredgold** [comment]
As covered in the [Installation troubleshooting guide here](https://silveredgold.github.io/beta-protection/guide/installation.html#can-t-import-placeholders-or-censor-local-images-with-brave), the Brave developers have disabled the File System Access API that extensions use to open files. That's needed for things like placeholder import and local censoring.

There's nothing I can do about it since the browser itself has disabled the entire API.
